version: '3.8'

services:

  mlflow:
    image: ghcr.io/mlflow/mlflow
    ports:
      - "5001:5000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./mlflow.db:/mlflow/mlflow.db
    command: mlflow server --backend-store-uri sqlite:///mlflow/mlflow.db --default-artifact-root /mlflow/mlruns --host 0.0.0.0 --port 5000

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
      
  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    depends_on:
      - prometheus


        #  drought_prediction:
        #    build:
        #      context: .
        #    ports:
        #      - "5002:5002"
        #    environment:
        #      - MODEL_PATH=/app/models/model_xgboost.bin
        #      - DV_PATH=/app/models/dv.bin
        #    depends_on:
        #      - mlflow
        #    expose:
        #      - "5002"


volumes:
  grafana-storage:

      # postgres:
      #   image: postgres:13
      #   environment:
      #     POSTGRES_DB: prefect
      #     POSTGRES_USER: prefectuser
      #     POSTGRES_PASSWORD: yourpassword
      #   volumes:
      #     - postgres_data:/var/lib/postgresql/data

      # prefect-server:
      #   image: prefecthq/prefect:2.0.4-python3.8
      #   command: prefect orion start
      #   environment:
      #     PREFECT_API_DATABASE_CONNECTION_URL: postgresql+psycopg2://prefectuser:yourpassword@postgres/prefect
      #   depends_on:
      #     - postgres
      #   ports:
      #     - "4200:4200"
      #   volumes:
      #     - ./scripts:/root/scripts

        #  prefect-agent:
        #    image: prefecthq/prefect:2.0.4-python3.8
        #    command: prefect work-queue create my_queue & prefect agent start
        #    environment:
        #      PREFECT_API_URL: http://prefect-server:4200/api
        #    depends_on:
        #      - prefect-server

      #volumes:
      #  postgres_data:
